### ISSUE TITLE
read_holding_registers returns None?

### ISSUE THREAD

**Issue by Rugiewitz** [sourceperl/pyModbusTCP#19]
Greetings!
I been playing around with my program and set up a server.
I have a thread that reads from the server every 0.5.
About 9/10 of the time when i run my program, it works perfectly fine. But there is a rare chance when doing
"regs = target.read_holding_registers(self.target_address, 1)" it will return None instead even tho my side program that shows me what's stored in the addresses state that it actually has a value there and isn't 0 or None. 

I tried to add some print statements onto my server to see what the results would be.
About the time when I get a None on a hold register, i get this message

```
Exception happened during processing of request from ('10.10.10.115', 50966)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/Library/Python/2.7/site-packages/pyModbusTCP/server.py", line 80, in handle
    rx_head = self.recv_all(7)
  File "/Library/Python/2.7/site-packages/pyModbusTCP/server.py", line 70, in recv_all
    data = self.request.recv(size, socket.MSG_WAITALL)
error: [Errno 54] Connection reset by peer
```

I was wondering if anybody can explain to me what's happening?

**Comment by Givo29** [comment]
@Rugiewitz I know this is quite late but if this is still an issue for you I might have a fix. If it's still a problem could you please provide your code and the register you're using?
